
- shell: >
    ./asadmin start-domain payaradomain &&
    ./asadmin
    --user {{ payara_admin_user }}
    --passwordfile pwdfile
    create-jdbc-connection-pool
    --datasourceclassname {{ item.classname }}
    --restype javax.sql.DataSource
    --property user={{ item.db.user }}:password={{ item.db.password }}:DatabaseName={{ item.db.name }}:ServerName={{ item.db.host }}:port={{ item.db.port }}
    {{ item.name }} &&
    ./asadmin stop-domain payaradomain
  args:
    chdir: "{{ payara_home }}/bin"
  with_items: "{{ payara_connection_pools }}"
  when: payara_connection_pools is defined

- shell: >
    ./asadmin start-domain payaradomain &&
    ./asadmin
    --user {{ payara_admin_user }}
    --passwordfile pwdfile
    create-jdbc-resource
    --connectionpoolid {{ item.connection_pool_id }}
    {{ item.name }} &&
    ./asadmin stop-domain payaradomain
  args:
    chdir: "{{ payara_home }}/bin"
  with_items: "{{ payara_jdbc_resources }}"
  when: payara_jdbc_resources is defined
