---
#
- template:
    src: admin-keyfile.j2
    dest: {{ payara_home }}/glassfish/domains/payaradomain/config/admin-keyfile

- template:
    src: pwdfile.j2
    dest: {{ payara_home}}/bin/pwdfile

- command: ./asadmin start-domain payaradomain
  args:
    chdir: "{{ payara_home }}/bin"

- command: ./asadmin --user admin --passwordfile pwdfile enable-secure-admin
  args:
    chdir: "{{ payara_home }}/bin"


- command: ./asadmin stop-domain payaradomain
  args:
    chdir: "{{ payara_home }}/bin"
