
- shell: >
    ./asadmin start-domain payaradomain &&
    ./asadmin create-jdbc-connection-pool
    --datasourceclassname {{ item.classname }}
    --restype javax.sql.DataSource
    --property user={{ item.db.user }}:password={{ item.db.password }}:DatabaseName={{ item.db.name }}:ServerName={{ item.db.host }}:port={{ item.db.port }}
    {{ item.name }} &&
    ./asadmin stop-domain payaradomain
  args:
    chdir: "{{ payara_home }}/bin"
  with_items: "{{ payara_datasources }}"
