---
#
- debug:
    msg: "{{ payara_url }} will be donwloaded in {{ payara_home }}"

- name: install payara
  unarchive:
    src: "{{ payara_url }}"
    dest: "{{ payara_base }}"
    copy: no
    creates: "{{ payara_home }}/bin/asadmin"
  become: yes
  when: payara_distribution != 'micro'

#- name: install payara micro
#  get_url:
#    src: "{{ payara_url }}"
#    dest: "{{ payara_home }}"
#    owner: "{{ ansible_user_id }}"
#    copy: no
#    creates: "{{ payara_home }}/bin/asadmin"
#  become: yes
#  when: payara_distribution == 'micro'
