---
#
- name: prepare payara home
  file:
    path: "{{ payara_home }}"
    state: directory
  become: yes

- debug:
    msg: "{{ payara_url }} will be donwloaded in {{ payara_home }}"

- name: install payara
  unarchive:
    src: "{{ payara_url }}"
    dest: "{{ payara_home }}"
    copy: no
