---
#
- name: prepare payara home
  file:
    path: "{{ payara_home }}"
    state: directory
    owner: "{{ ansible_user_id }}"
  become: yes

- name: install unzip
  package: name=unzip state=latest
  become: yes

- debug:
    msg: "{{ payara_url }} will be donwloaded in {{ payara_home }}"

- name: install payara
  unarchive:
    src: "{{ payara_url }}"
    dest: "{{ payara_home }}"
    owner: "{{ ansible_user_id }}"
    copy: no
  become: yes
