---
# tasks file for payara
- include: prepare.yml
  become: yes

- include_vars: payara-{{ payara_distribution }}-{{ payara_multilanguage }}-ml.yml

- include: install.yml
  become: yes

- include: configure.yml
  become: yes
  become_user: "{{ payara_user }}"
