Vagrant.configure(2) do |config|

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.galaxy_role_file = "roles.yml"
  end

  config.vm.define "test01" do |node|
    node.vm.box = "jeqo/oracle-jdk-8-centos7"
  end

  config.vm.define "test02" do |node|
    node.vm.box = "jeqo/oracle-jdk-8-centos7"
  end

  config.vm.define "test03" do |node|
    node.vm.box = "jeqo/oracle-jdk-8-ubuntu14"
  end

  config.vm.define "test04" do |node|
    node.vm.box = "jeqo/oracle-jdk-8-ubuntu14"
  end
end
